#!/usr/bin/env ruby

# frozen_string_literal: true
require 'optparse'
require 'optparse/time'

class BkmrqCli
  MAN = <<-MAN
  Bkmrq - Export your bookmarks to markdown
  Usage: bkmrq [--output <filename.md>] [--input <bookmarks.json>]

  # Options
  --output, -o    sets the export file path & name
  --input, -i     set the path to the bookmarks json file generated by your browser
  --edit, -e      will open the file in an $EDITOR after export

  # Supported Browsers
  - Brave
  MAN

  def initialize
    OptionParser.new do |parser|
      parser.on('-t', '--time')   { |option| p option }
      parser.on('-o', '--output') { |option| p opts[:output] = option }
      parser.on('-i', '--input')  { |option| p opts[:input] = option }
      parser.on('-i', '--input')  { |option| p opts[:input] = option }
    end.parse!
  end

  def print_man
    puts(MAN)
  end
end
