# frozen_string_literal: true

# Bookmarks Manual
module Bkmrq
  class Manual
    BANNER = <<-MAN
    Bkmrq - Export your bookmarks to markdown

    # Supported Browsers
    - brave
    - chromium
    MAN

    OPTS = [
      ['-F', '--input-file',  String, 'Bookmarks file generated by your browser. (JSON FORMAT ONLY)'],
      ['-O', '--output-file', String, 'Filepath for markdown generated by Bkmrq'],
      ['-B', '--browser',     String, 'Browser (Loads Default Configs)'],
      ['-E', '--edit',                'Load Generated Markdown in $EDITOR (will not persist generated output)'],
      ['-H', '--help',                'Print Bkmrq Manual']
    ].freeze
  end
end
